name: build
on:
  - pull_request
  - push
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@master }
      - { uses: actions/setup-node@master, with: { node-version: "12" } }
      - { run: "yarn install" }
      - {
          uses: paambaati/codeclimate-action@v2.4.0,
          env:
            {
              CC_TEST_REPORTER_ID: "${{ secrets.CodeClimateReporterId }}",
              CI: true,
            },
          with:
            {
              coverageCommand: "yarn run coverage",
              debug: true,
              coverageLocations: "./artificial-artist-fe/coverage/lcov.info:lcov",
            },
        }
